spring.rabbitmq.host=192.168.1.122
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ?? OpenAI ??????? Groq
spring.ai.openai.base-url=https://groq.com
groq.api.key=your_api_key_placeholder
spring.ai.openai.chat.options.model=qwen/qwen3.8-27b
spring.ai.openai.chat.options.temperature=0.2
